#ifndef WIDGETHEADER_H
#define WIDGETHEADER_H

#include <QMap>
#include <QString>

namespace  DR_SPACE {

enum E_WIDGET {
    E_MAIN_WINDOW,
    E_TITLE_WIDGET,
    E_PLAY_CONTROL_WIDGET,
    E_NOTE_TIP_WIDGET,
    E_MAIN_OPERATION_WIDGET,
    E_LEFT_SLIDERBAR_WIDGET,
    E_HOME_WIDGET,
    E_FIND_WIDGET,
    E_FILE_VIEW_WIDGET,
    E_FILE_ATTR_WIDGET,
    E_DOC_SHOW_SHELL_WIDGET,
    E_CENTRAL_WIDGET,
    E_MAIN_TAB_WIDGET,
    E_MAIN_SPLITTER,
    E_THUMBAIL_WIDGET,
    E_THUMBAIL_ITEM_WIDGET,
    E_PAGE_WIDGET,
    E_SEARCH_RES_WIDGET,
    E_SEARCH_ITEM_WIDGET,
    E_SPINNER_WIDGET,
    E_NOTE_VIEW_WIDGET,
    E_NOTE_WIDGET,
    E_NOTE_ITEM_WIDGET,
    E_CATALOG_WIDGET,
    E_BOOKMARK_WIDGET,
    E_BOOKMARK_ITEM_WIDGET
};

enum E_MENU {
    E_TITLE_MENU,
    E_TEXT_OPERATION_MENU,
    E_SCALE_MENU,
    E_HANDLE_MENU,
    E_FONT_MENU,
    E_DEFAULT_OPERATION_MENU,
    E_NOTE_MENU,
    E_BOOKMARK_MENU
};

}

#endif // WIDGETHEADER_H
