
#ifndef UT_DEFINES_TEST_H
#define UT_DEFINES_TEST_H

#define UT_SHEETSIDEBAR_TEST
#define UT_UTILS_TEST
#define UT_MAINWINDOW_TEST
#define UT_WIDGETS_TEST
#define UT_UIFRAME_TEST
#define UT_DOCSHEET_TEST

#endif // UT_DEFINES_TEST_H
