[Menu Entry]
Actions=Zero
Version=1.0

[Menu Action Zero]
Exec=deepin-reader-batchprint %F
MimeType=application/pdf:application/vnd.openxmlformats-officedocument.wordprocessingml.document:application/wps-office.docx:image/vnd.djvu:application/vnd.ms-xpsdocument:application/oxps
Name=Batch Print
PosNum=6
Separator=Top
X-DFM-ExcludeMimeTypes=inode/directory:application/x-desktop
X-DFM-MenuTypes=SingleFile:MultiFiles
X-DFM-SupportSchemes=file
Name[zh_CN]=批量打印
Name[zh_HK]=批量打印
Name[zh_TW]=批量打印
